// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentFailedAuthAttempts = `-- name: CountRecentFailedAuthAttempts :one
SELECT count(*)::bigint
FROM auth.auth_attempt
WHERE success = false
  AND created_at >= now() - interval '15 minutes'
  AND (identifier = lower($1) OR source_ip = $2)
`

type CountRecentFailedAuthAttemptsParams struct {
	Identifier string
	SourceIp   *netip.Addr
}

func (q *Queries) CountRecentFailedAuthAttempts(ctx context.Context, arg CountRecentFailedAuthAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedAuthAttempts, arg.Identifier, arg.SourceIp)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentPasswordRecoveryAttempts = `-- name: CountRecentPasswordRecoveryAttempts :one
SELECT count(*)::bigint
FROM auth.password_recovery_attempt
WHERE operation = $1
  AND created_at >= now() - interval '15 minutes'
  AND (
      ($2::text <> '' AND identifier = lower($2::text))
      OR ($3::inet IS NOT NULL AND source_ip = $3::inet)
  )
`

type CountRecentPasswordRecoveryAttemptsParams struct {
	Operation  string
	Identifier string
	SourceIp   *netip.Addr
}

func (q *Queries) CountRecentPasswordRecoveryAttempts(ctx context.Context, arg CountRecentPasswordRecoveryAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPasswordRecoveryAttempts, arg.Operation, arg.Identifier, arg.SourceIp)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_log (
    organization_id, actor_user_id, action, target_type, target_id,
    after_data, source_ip, correlation_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
`

type CreateAuditEventParams struct {
	OrganizationID pgtype.UUID
	ActorUserID    pgtype.UUID
	Action         string
	TargetType     string
	TargetID       pgtype.UUID
	AfterData      []byte
	SourceIp       *netip.Addr
	CorrelationID  pgtype.UUID
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.AfterData,
		arg.SourceIp,
		arg.CorrelationID,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO auth.password_reset_token (
    id, organization_id, user_id, token_hash, expires_at, requested_ip
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreatePasswordResetTokenParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	TokenHash      []byte
	ExpiresAt      pgtype.Timestamptz
	RequestedIp    *netip.Addr
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RequestedIp,
	)
	return err
}

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO auth.user_session (
    id, organization_id, user_id, token_hash, csrf_hash, expires_at, idle_expires_at,
    client_ip, user_agent
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
`

type CreateUserSessionParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	TokenHash      []byte
	CsrfHash       []byte
	ExpiresAt      pgtype.Timestamptz
	IdleExpiresAt  pgtype.Timestamptz
	ClientIp       *netip.Addr
	UserAgent      string
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.Exec(ctx, createUserSession,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfHash,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.ClientIp,
		arg.UserAgent,
	)
	return err
}

const getActivePasswordResetToken = `-- name: GetActivePasswordResetToken :one
SELECT t.id AS token_id, t.organization_id, t.user_id, u.email
FROM auth.password_reset_token t
JOIN auth.app_user u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.used_at IS NULL
  AND t.expires_at > now()
  AND u.status = 'ACTIVE'
LIMIT 1
FOR UPDATE OF t
`

type GetActivePasswordResetTokenRow struct {
	TokenID        pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Email          string
}

func (q *Queries) GetActivePasswordResetToken(ctx context.Context, tokenHash []byte) (GetActivePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getActivePasswordResetToken, tokenHash)
	var i GetActivePasswordResetTokenRow
	err := row.Scan(
		&i.TokenID,
		&i.OrganizationID,
		&i.UserID,
		&i.Email,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id AS session_id, s.organization_id, s.user_id, s.csrf_hash,
       s.expires_at, s.idle_expires_at, u.email, u.display_name, u.password_hash
FROM auth.user_session s
JOIN auth.app_user u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND s.idle_expires_at > now()
  AND u.status = 'ACTIVE'
LIMIT 1
`

type GetActiveSessionRow struct {
	SessionID      pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	CsrfHash       []byte
	ExpiresAt      pgtype.Timestamptz
	IdleExpiresAt  pgtype.Timestamptz
	Email          string
	DisplayName    string
	PasswordHash   string
}

func (q *Queries) GetActiveSession(ctx context.Context, tokenHash []byte) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, tokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.OrganizationID,
		&i.UserID,
		&i.CsrfHash,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
	)
	return i, err
}

const getLoginUser = `-- name: GetLoginUser :one
SELECT id, organization_id, email, display_name, password_hash, status,
       failed_login_count, locked_until
FROM auth.app_user
WHERE email = lower($1)
   OR username = lower($1)
LIMIT 1
`

type GetLoginUserRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Email            string
	DisplayName      string
	PasswordHash     string
	Status           string
	FailedLoginCount int32
	LockedUntil      pgtype.Timestamptz
}

func (q *Queries) GetLoginUser(ctx context.Context, identifier string) (GetLoginUserRow, error) {
	row := q.db.QueryRow(ctx, getLoginUser, identifier)
	var i GetLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const getPasswordResetUser = `-- name: GetPasswordResetUser :one
SELECT id, organization_id, email, status
FROM auth.app_user
WHERE email = lower($1)
LIMIT 1
`

type GetPasswordResetUserRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Email          string
	Status         string
}

func (q *Queries) GetPasswordResetUser(ctx context.Context, email string) (GetPasswordResetUserRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetUser, email)
	var i GetPasswordResetUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Status,
	)
	return i, err
}

const invalidatePasswordResetTokens = `-- name: InvalidatePasswordResetTokens :exec
UPDATE auth.password_reset_token
SET used_at = COALESCE(used_at, now())
WHERE user_id = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidatePasswordResetTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetTokens, userID)
	return err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, expires_at, idle_expires_at, last_seen_at, revoked_at,
       client_ip, user_agent, created_at
FROM auth.user_session
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListUserSessionsRow struct {
	ID            pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	ClientIp      *netip.Addr
	UserAgent     string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.ClientIp,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE auth.password_reset_token
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, tokenID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, tokenID)
	return err
}

const recordAuthAttempt = `-- name: RecordAuthAttempt :exec
INSERT INTO auth.auth_attempt (identifier, source_ip, success)
VALUES (lower($1), $2, $3)
`

type RecordAuthAttemptParams struct {
	Identifier string
	SourceIp   *netip.Addr
	Success    bool
}

func (q *Queries) RecordAuthAttempt(ctx context.Context, arg RecordAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAuthAttempt, arg.Identifier, arg.SourceIp, arg.Success)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE auth.app_user
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE
        WHEN failed_login_count + 1 >= 5 THEN now() + interval '15 minutes'
        ELSE locked_until
    END,
    updated_at = now()
WHERE id = $1
RETURNING failed_login_count, locked_until
`

type RecordLoginFailureRow struct {
	FailedLoginCount int32
	LockedUntil      pgtype.Timestamptz
}

func (q *Queries) RecordLoginFailure(ctx context.Context, userID pgtype.UUID) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, userID)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE auth.app_user
SET failed_login_count = 0,
    locked_until = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, userID)
	return err
}

const recordPasswordRecoveryAttempt = `-- name: RecordPasswordRecoveryAttempt :exec
INSERT INTO auth.password_recovery_attempt (operation, identifier, source_ip, success)
VALUES ($1, lower($2), $3, $4)
`

type RecordPasswordRecoveryAttemptParams struct {
	Operation  string
	Identifier string
	SourceIp   *netip.Addr
	Success    bool
}

func (q *Queries) RecordPasswordRecoveryAttempt(ctx context.Context, arg RecordPasswordRecoveryAttemptParams) error {
	_, err := q.db.Exec(ctx, recordPasswordRecoveryAttempt,
		arg.Operation,
		arg.Identifier,
		arg.SourceIp,
		arg.Success,
	)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth.user_session
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeOwnedSession = `-- name: RevokeOwnedSession :one
UPDATE auth.user_session
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
  AND user_id = $2
RETURNING id
`

type RevokeOwnedSessionParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) RevokeOwnedSession(ctx context.Context, arg RevokeOwnedSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, revokeOwnedSession, arg.SessionID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth.user_session
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, sessionID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE auth.user_session
SET last_seen_at = now(),
    idle_expires_at = LEAST(expires_at, now() + $1::bigint * interval '1 second')
WHERE id = $2
  AND last_seen_at < now() - interval '1 minute'
`

type TouchSessionParams struct {
	IdleSeconds int64
	SessionID   pgtype.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.IdleSeconds, arg.SessionID)
	return err
}

const updatePasswordAndRevokeOtherSessions = `-- name: UpdatePasswordAndRevokeOtherSessions :exec
WITH changed AS (
    UPDATE auth.app_user AS u
    SET password_hash = $3,
        password_changed_at = now(),
        updated_at = now()
    WHERE u.id = $1
)
UPDATE auth.user_session AS s
SET revoked_at = COALESCE(s.revoked_at, now())
WHERE s.user_id = $1
  AND s.id <> $2
  AND s.revoked_at IS NULL
`

type UpdatePasswordAndRevokeOtherSessionsParams struct {
	UserID           pgtype.UUID
	CurrentSessionID pgtype.UUID
	PasswordHash     string
}

func (q *Queries) UpdatePasswordAndRevokeOtherSessions(ctx context.Context, arg UpdatePasswordAndRevokeOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, updatePasswordAndRevokeOtherSessions, arg.UserID, arg.CurrentSessionID, arg.PasswordHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth.app_user
SET password_hash = $1,
    password_changed_at = now(),
    failed_login_count = 0,
    locked_until = NULL,
    updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UserID       pgtype.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UserID)
	return err
}
