// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: core.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasOrganizationPermission = `-- name: HasOrganizationPermission :one
SELECT EXISTS (
    SELECT 1 FROM user_role ur
    JOIN role r ON r.id = ur.role_id
    JOIN role_permission rp ON rp.role_id = ur.role_id
    JOIN permission pm ON pm.id = rp.permission_id
    WHERE ur.user_id = $1
      AND pm.action = $2
      AND pm.resource_type = $3
      AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
      AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
      AND ur.plant_id IS NULL
      AND (ur.organization_id IS NULL OR ur.organization_id = $4)
)::boolean
`

type HasOrganizationPermissionParams struct {
	UserID         pgtype.UUID
	Action         string
	ResourceType   string
	OrganizationID pgtype.UUID
}

func (q *Queries) HasOrganizationPermission(ctx context.Context, arg HasOrganizationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrganizationPermission,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.OrganizationID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasUserPermission = `-- name: HasUserPermission :one
SELECT EXISTS (
    SELECT 1 FROM user_role ur
    JOIN role r ON r.id = ur.role_id
    JOIN role_permission rp ON rp.role_id = ur.role_id
    JOIN permission pm ON pm.id = rp.permission_id
    WHERE ur.user_id = $1
      AND pm.action = $2
      AND pm.resource_type = $3
      AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
      AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
)::boolean
`

type HasUserPermissionParams struct {
	UserID       pgtype.UUID
	Action       string
	ResourceType string
}

func (q *Queries) HasUserPermission(ctx context.Context, arg HasUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserPermission, arg.UserID, arg.Action, arg.ResourceType)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
