// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEventFull = `-- name: CreateAuditEventFull :exec
INSERT INTO audit_log (
    organization_id, actor_user_id, action, target_type, target_id,
    before_data, after_data, source_ip, correlation_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
`

type CreateAuditEventFullParams struct {
	OrganizationID pgtype.UUID
	ActorUserID    pgtype.UUID
	Action         string
	TargetType     string
	TargetID       pgtype.UUID
	BeforeData     []byte
	AfterData      []byte
	SourceIp       *netip.Addr
	CorrelationID  pgtype.UUID
}

func (q *Queries) CreateAuditEventFull(ctx context.Context, arg CreateAuditEventFullParams) error {
	_, err := q.db.Exec(ctx, createAuditEventFull,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeData,
		arg.AfterData,
		arg.SourceIp,
		arg.CorrelationID,
	)
	return err
}

const createPlant = `-- name: CreatePlant :one
INSERT INTO plant.plant (
    id, organization_id, code, name, timezone, latitude, longitude,
    installed_dc_kw, installed_ac_kw
) VALUES (
    $1, $2, $3, $4, $5,
    $6::double precision, $7::double precision,
    $8::double precision, $9::double precision
)
RETURNING id, organization_id, code, name, timezone, latitude, longitude,
          installed_dc_kw,
          installed_ac_kw,
          image_url,
          is_active, created_at, updated_at
`

type CreatePlantParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
	Timezone       string
	Latitude       pgtype.Float8
	Longitude      pgtype.Float8
	InstalledDcKw  pgtype.Float8
	InstalledAcKw  pgtype.Float8
}

type CreatePlantRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
	Timezone       string
	Latitude       pgtype.Float8
	Longitude      pgtype.Float8
	InstalledDcKw  pgtype.Numeric
	InstalledAcKw  pgtype.Numeric
	ImageUrl       pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) (CreatePlantRow, error) {
	row := q.db.QueryRow(ctx, createPlant,
		arg.ID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Timezone,
		arg.Latitude,
		arg.Longitude,
		arg.InstalledDcKw,
		arg.InstalledAcKw,
	)
	var i CreatePlantRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.InstalledDcKw,
		&i.InstalledAcKw,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedPlant = `-- name: GetAuthorizedPlant :one
SELECT p.id, p.organization_id, o.name AS organization_name,
       p.code, p.name, p.timezone, p.latitude, p.longitude,
       p.installed_dc_kw,
       p.installed_ac_kw,
       p.image_url,
       p.is_active, p.created_at, p.updated_at
FROM plant.plant p
JOIN organization o ON o.id = p.organization_id
WHERE p.id = $1
  AND EXISTS (
      SELECT 1 FROM auth.user_role ur
      JOIN auth.role r ON r.id = ur.role_id
      JOIN auth.role_permission rp ON rp.role_id = ur.role_id
      JOIN auth.permission pm ON pm.id = rp.permission_id
      WHERE ur.user_id = $2
        AND pm.action = $3 AND pm.resource_type = 'plant'
        AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
        AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
        AND (ur.organization_id IS NULL OR ur.organization_id = p.organization_id)
        AND (ur.plant_id IS NULL OR ur.plant_id = p.id)
  )
LIMIT 1
`

type GetAuthorizedPlantParams struct {
	PlantID pgtype.UUID
	UserID  pgtype.UUID
	Action  string
}

type GetAuthorizedPlantRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	OrganizationName string
	Code             string
	Name             string
	Timezone         string
	Latitude         pgtype.Float8
	Longitude        pgtype.Float8
	InstalledDcKw    pgtype.Numeric
	InstalledAcKw    pgtype.Numeric
	ImageUrl         pgtype.Text
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAuthorizedPlant(ctx context.Context, arg GetAuthorizedPlantParams) (GetAuthorizedPlantRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedPlant, arg.PlantID, arg.UserID, arg.Action)
	var i GetAuthorizedPlantRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.Code,
		&i.Name,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.InstalledDcKw,
		&i.InstalledAcKw,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedPlantForUpdate = `-- name: GetAuthorizedPlantForUpdate :one
SELECT p.id, p.organization_id, o.name AS organization_name,
       p.code, p.name, p.timezone, p.latitude, p.longitude,
       p.installed_dc_kw,
       p.installed_ac_kw,
       p.image_url,
       p.is_active, p.created_at, p.updated_at
FROM plant.plant p
JOIN organization o ON o.id = p.organization_id
WHERE p.id = $1
  AND EXISTS (
      SELECT 1 FROM auth.user_role ur
      JOIN auth.role r ON r.id = ur.role_id
      JOIN auth.role_permission rp ON rp.role_id = ur.role_id
      JOIN auth.permission pm ON pm.id = rp.permission_id
      WHERE ur.user_id = $2
        AND pm.action = 'update' AND pm.resource_type = 'plant'
        AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
        AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
        AND (ur.organization_id IS NULL OR ur.organization_id = p.organization_id)
        AND (ur.plant_id IS NULL OR ur.plant_id = p.id)
  )
LIMIT 1
FOR UPDATE OF p
`

type GetAuthorizedPlantForUpdateParams struct {
	PlantID pgtype.UUID
	UserID  pgtype.UUID
}

type GetAuthorizedPlantForUpdateRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	OrganizationName string
	Code             string
	Name             string
	Timezone         string
	Latitude         pgtype.Float8
	Longitude        pgtype.Float8
	InstalledDcKw    pgtype.Numeric
	InstalledAcKw    pgtype.Numeric
	ImageUrl         pgtype.Text
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAuthorizedPlantForUpdate(ctx context.Context, arg GetAuthorizedPlantForUpdateParams) (GetAuthorizedPlantForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedPlantForUpdate, arg.PlantID, arg.UserID)
	var i GetAuthorizedPlantForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.Code,
		&i.Name,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.InstalledDcKw,
		&i.InstalledAcKw,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT name FROM organization WHERE id = $1 AND is_active = true
`

func (q *Queries) GetOrganizationName(ctx context.Context, organizationID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationName, organizationID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const hasOrganizationPermission = `-- name: HasOrganizationPermission :one
SELECT EXISTS (
    SELECT 1 FROM auth.user_role ur
    JOIN auth.role r ON r.id = ur.role_id
    JOIN auth.role_permission rp ON rp.role_id = ur.role_id
    JOIN auth.permission pm ON pm.id = rp.permission_id
    WHERE ur.user_id = $1
      AND pm.action = $2
      AND pm.resource_type = $3
      AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
      AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
      AND ur.plant_id IS NULL
      AND (ur.organization_id IS NULL OR ur.organization_id = $4)
)::boolean
`

type HasOrganizationPermissionParams struct {
	UserID         pgtype.UUID
	Action         string
	ResourceType   string
	OrganizationID pgtype.UUID
}

func (q *Queries) HasOrganizationPermission(ctx context.Context, arg HasOrganizationPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOrganizationPermission,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.OrganizationID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasUserPermission = `-- name: HasUserPermission :one
SELECT EXISTS (
    SELECT 1 FROM auth.user_role ur
    JOIN auth.role r ON r.id = ur.role_id
    JOIN auth.role_permission rp ON rp.role_id = ur.role_id
    JOIN auth.permission pm ON pm.id = rp.permission_id
    WHERE ur.user_id = $1
      AND pm.action = $2
      AND pm.resource_type = $3
      AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
      AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
)::boolean
`

type HasUserPermissionParams struct {
	UserID       pgtype.UUID
	Action       string
	ResourceType string
}

func (q *Queries) HasUserPermission(ctx context.Context, arg HasUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserPermission, arg.UserID, arg.Action, arg.ResourceType)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAuthorizedPlants = `-- name: ListAuthorizedPlants :many
SELECT p.id, p.organization_id, o.name AS organization_name,
       p.code, p.name, p.timezone, p.latitude, p.longitude,
       p.installed_dc_kw,
       p.installed_ac_kw,
       p.image_url,
       p.is_active, p.created_at, p.updated_at
FROM plant.plant p
JOIN organization o ON o.id = p.organization_id
WHERE EXISTS (
    SELECT 1 FROM auth.user_role ur
    JOIN auth.role r ON r.id = ur.role_id
    JOIN auth.role_permission rp ON rp.role_id = ur.role_id
    JOIN auth.permission pm ON pm.id = rp.permission_id
    WHERE ur.user_id = $1
      AND pm.action = 'read' AND pm.resource_type = 'plant'
      AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
      AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
      AND (ur.organization_id IS NULL OR ur.organization_id = p.organization_id)
      AND (ur.plant_id IS NULL OR ur.plant_id = p.id)
)
ORDER BY o.name, p.name, p.id
LIMIT 200
`

type ListAuthorizedPlantsRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	OrganizationName string
	Code             string
	Name             string
	Timezone         string
	Latitude         pgtype.Float8
	Longitude        pgtype.Float8
	InstalledDcKw    pgtype.Numeric
	InstalledAcKw    pgtype.Numeric
	ImageUrl         pgtype.Text
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListAuthorizedPlants(ctx context.Context, userID pgtype.UUID) ([]ListAuthorizedPlantsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedPlants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedPlantsRow
	for rows.Next() {
		var i ListAuthorizedPlantsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Code,
			&i.Name,
			&i.Timezone,
			&i.Latitude,
			&i.Longitude,
			&i.InstalledDcKw,
			&i.InstalledAcKw,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlant = `-- name: UpdatePlant :one
UPDATE plant.plant
SET code = $1, name = $2, timezone = $3,
    latitude = $4::double precision,
    longitude = $5::double precision,
    installed_dc_kw = $6::double precision,
    installed_ac_kw = $7::double precision,
    is_active = $8, updated_at = now()
WHERE id = $9
RETURNING id, organization_id, code, name, timezone, latitude, longitude,
          installed_dc_kw,
          installed_ac_kw,
          image_url,
          is_active, created_at, updated_at
`

type UpdatePlantParams struct {
	Code          string
	Name          string
	Timezone      string
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
	InstalledDcKw pgtype.Float8
	InstalledAcKw pgtype.Float8
	IsActive      bool
	ID            pgtype.UUID
}

type UpdatePlantRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
	Timezone       string
	Latitude       pgtype.Float8
	Longitude      pgtype.Float8
	InstalledDcKw  pgtype.Numeric
	InstalledAcKw  pgtype.Numeric
	ImageUrl       pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdatePlant(ctx context.Context, arg UpdatePlantParams) (UpdatePlantRow, error) {
	row := q.db.QueryRow(ctx, updatePlant,
		arg.Code,
		arg.Name,
		arg.Timezone,
		arg.Latitude,
		arg.Longitude,
		arg.InstalledDcKw,
		arg.InstalledAcKw,
		arg.IsActive,
		arg.ID,
	)
	var i UpdatePlantRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Timezone,
		&i.Latitude,
		&i.Longitude,
		&i.InstalledDcKw,
		&i.InstalledAcKw,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
