// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDashboardPlantStatus = `-- name: ListDashboardPlantStatus :many
SELECT p.id AS plant_id, p.code, p.name, p.timezone, p.is_active,
       count(d.id)::bigint AS device_count,
       count(d.id) FILTER (WHERE d.is_active)::bigint AS active_device_count,
       count(tl.device_id) FILTER (WHERE d.is_active)::bigint AS reporting_device_count,
       count(tl.device_id) FILTER (WHERE d.is_active AND tl.observed_at < $1)::bigint AS stale_device_count,
       count(d.id) FILTER (WHERE d.is_active AND tl.device_id IS NULL)::bigint AS offline_device_count,
       max(tl.observed_at) FILTER (WHERE d.is_active) AS last_observed_at
FROM plant p
LEFT JOIN device d ON d.organization_id = p.organization_id AND d.plant_id = p.id
LEFT JOIN telemetry_latest tl ON tl.organization_id = d.organization_id AND tl.device_id = d.id
WHERE EXISTS (
    SELECT 1 FROM user_role ur
    JOIN role r ON r.id = ur.role_id
    JOIN role_permission rp ON rp.role_id = ur.role_id
    JOIN permission pm ON pm.id = rp.permission_id
    WHERE ur.user_id = $2
      AND pm.action = 'read' AND pm.resource_type = 'device'
      AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
      AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
      AND (ur.organization_id IS NULL OR ur.organization_id = p.organization_id)
      AND (ur.plant_id IS NULL OR ur.plant_id = p.id)
)
GROUP BY p.id, p.code, p.name, p.timezone, p.is_active
ORDER BY p.name, p.code, p.id
LIMIT 200
`

type ListDashboardPlantStatusParams struct {
	StaleBefore pgtype.Timestamptz
	UserID      pgtype.UUID
}

type ListDashboardPlantStatusRow struct {
	PlantID              pgtype.UUID
	Code                 string
	Name                 string
	Timezone             string
	IsActive             bool
	DeviceCount          int64
	ActiveDeviceCount    int64
	ReportingDeviceCount int64
	StaleDeviceCount     int64
	OfflineDeviceCount   int64
	LastObservedAt       pgtype.Timestamptz
}

func (q *Queries) ListDashboardPlantStatus(ctx context.Context, arg ListDashboardPlantStatusParams) ([]ListDashboardPlantStatusRow, error) {
	rows, err := q.db.Query(ctx, listDashboardPlantStatus, arg.StaleBefore, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardPlantStatusRow
	for rows.Next() {
		var i ListDashboardPlantStatusRow
		if err := rows.Scan(
			&i.PlantID, &i.Code, &i.Name, &i.Timezone, &i.IsActive,
			&i.DeviceCount, &i.ActiveDeviceCount, &i.ReportingDeviceCount,
			&i.StaleDeviceCount, &i.OfflineDeviceCount, &i.LastObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDashboard = `-- name: GetUserDashboard :one
SELECT id, organization_id, owner_user_id, name, layouts, version,
       widget_configs, published_layouts, published_widget_configs,
       published_version, published_from_version, published_at,
       created_at, updated_at
FROM user_dashboard
WHERE organization_id = $1
  AND owner_user_id = $2
LIMIT 1
`

type GetUserDashboardParams struct {
	OrganizationID pgtype.UUID
	OwnerUserID    pgtype.UUID
}

type GetUserDashboardRow struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	OwnerUserID            pgtype.UUID
	Name                   string
	Layouts                []byte
	Version                int32
	WidgetConfigs          []byte
	PublishedLayouts       []byte
	PublishedWidgetConfigs []byte
	PublishedVersion       int32
	PublishedFromVersion   int32
	PublishedAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) GetUserDashboard(ctx context.Context, arg GetUserDashboardParams) (GetUserDashboardRow, error) {
	row := q.db.QueryRow(ctx, getUserDashboard, arg.OrganizationID, arg.OwnerUserID)
	var i GetUserDashboardRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.OwnerUserID, &i.Name, &i.Layouts, &i.Version, &i.WidgetConfigs, &i.PublishedLayouts, &i.PublishedWidgetConfigs, &i.PublishedVersion, &i.PublishedFromVersion, &i.PublishedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getUserDashboardForUpdate = `-- name: GetUserDashboardForUpdate :one
SELECT id, organization_id, owner_user_id, name, layouts, version,
       widget_configs, published_layouts, published_widget_configs,
       published_version, published_from_version, published_at,
       created_at, updated_at
FROM user_dashboard
WHERE organization_id = $1
  AND owner_user_id = $2
LIMIT 1
FOR UPDATE
`

type GetUserDashboardForUpdateParams = GetUserDashboardParams
type GetUserDashboardForUpdateRow = GetUserDashboardRow

func (q *Queries) GetUserDashboardForUpdate(ctx context.Context, arg GetUserDashboardForUpdateParams) (GetUserDashboardForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserDashboardForUpdate, arg.OrganizationID, arg.OwnerUserID)
	var i GetUserDashboardForUpdateRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.OwnerUserID, &i.Name, &i.Layouts, &i.Version, &i.WidgetConfigs, &i.PublishedLayouts, &i.PublishedWidgetConfigs, &i.PublishedVersion, &i.PublishedFromVersion, &i.PublishedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createUserDashboard = `-- name: CreateUserDashboard :one
INSERT INTO user_dashboard (id, organization_id, owner_user_id, layouts, widget_configs)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, owner_user_id, name, layouts, version,
          widget_configs, published_layouts, published_widget_configs,
          published_version, published_from_version, published_at,
          created_at, updated_at
`

type CreateUserDashboardParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OwnerUserID    pgtype.UUID
	Layouts        []byte
	WidgetConfigs  []byte
}

type CreateUserDashboardRow = GetUserDashboardRow

func (q *Queries) CreateUserDashboard(ctx context.Context, arg CreateUserDashboardParams) (CreateUserDashboardRow, error) {
	row := q.db.QueryRow(ctx, createUserDashboard, arg.ID, arg.OrganizationID, arg.OwnerUserID, arg.Layouts, arg.WidgetConfigs)
	var i CreateUserDashboardRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.OwnerUserID, &i.Name, &i.Layouts, &i.Version, &i.WidgetConfigs, &i.PublishedLayouts, &i.PublishedWidgetConfigs, &i.PublishedVersion, &i.PublishedFromVersion, &i.PublishedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const updateUserDashboard = `-- name: UpdateUserDashboard :one
UPDATE user_dashboard
SET layouts = $1, widget_configs = $2,
    version = version + 1, updated_at = now()
WHERE id = $3
RETURNING id, organization_id, owner_user_id, name, layouts, version,
          widget_configs, published_layouts, published_widget_configs,
          published_version, published_from_version, published_at,
          created_at, updated_at
`

type UpdateUserDashboardParams struct {
	Layouts       []byte
	WidgetConfigs []byte
	ID            pgtype.UUID
}

type UpdateUserDashboardRow = GetUserDashboardRow

func (q *Queries) UpdateUserDashboard(ctx context.Context, arg UpdateUserDashboardParams) (UpdateUserDashboardRow, error) {
	row := q.db.QueryRow(ctx, updateUserDashboard, arg.Layouts, arg.WidgetConfigs, arg.ID)
	var i UpdateUserDashboardRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.OwnerUserID, &i.Name, &i.Layouts, &i.Version, &i.WidgetConfigs, &i.PublishedLayouts, &i.PublishedWidgetConfigs, &i.PublishedVersion, &i.PublishedFromVersion, &i.PublishedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const publishUserDashboard = `-- name: PublishUserDashboard :one
UPDATE user_dashboard
SET published_layouts = layouts,
    published_widget_configs = widget_configs,
    published_version = published_version + 1,
    published_from_version = version,
    published_at = now()
WHERE id = $1
RETURNING id, organization_id, owner_user_id, name, layouts, version,
          widget_configs, published_layouts, published_widget_configs,
          published_version, published_from_version, published_at,
          created_at, updated_at
`

func (q *Queries) PublishUserDashboard(ctx context.Context, id pgtype.UUID) (GetUserDashboardRow, error) {
	row := q.db.QueryRow(ctx, publishUserDashboard, id)
	var i GetUserDashboardRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.OwnerUserID, &i.Name, &i.Layouts, &i.Version, &i.WidgetConfigs, &i.PublishedLayouts, &i.PublishedWidgetConfigs, &i.PublishedVersion, &i.PublishedFromVersion, &i.PublishedAt, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
