// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthorizedDeviceForUpdate = `-- name: GetAuthorizedDeviceForUpdate :one
SELECT d.id, d.organization_id, d.plant_id, d.external_id, d.name,
       d.device_model_id, dm.manufacturer, dm.model, dm.device_type,
       dm.source_type_id, d.is_active, d.created_at, d.updated_at
FROM device d
JOIN device_model dm ON dm.id = d.device_model_id
WHERE d.id = $1
  AND d.plant_id = $2
  AND EXISTS (
      SELECT 1 FROM user_role ur
      JOIN role r ON r.id = ur.role_id
      JOIN role_permission rp ON rp.role_id = ur.role_id
      JOIN permission pm ON pm.id = rp.permission_id
      WHERE ur.user_id = $3
        AND pm.action = 'update'
        AND pm.resource_type = 'device'
        AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
        AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
        AND (ur.organization_id IS NULL OR ur.organization_id = d.organization_id)
        AND (ur.plant_id IS NULL OR ur.plant_id = d.plant_id)
  )
LIMIT 1
FOR UPDATE OF d
`

type GetAuthorizedDeviceForUpdateParams struct {
	DeviceID pgtype.UUID
	PlantID  pgtype.UUID
	UserID   pgtype.UUID
}

type GetAuthorizedDeviceForUpdateRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	ExternalID     string
	Name           string
	DeviceModelID  pgtype.UUID
	Manufacturer   string
	Model          string
	DeviceType     string
	SourceTypeID   pgtype.Int4
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetAuthorizedDeviceForUpdate(ctx context.Context, arg GetAuthorizedDeviceForUpdateParams) (GetAuthorizedDeviceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedDeviceForUpdate, arg.DeviceID, arg.PlantID, arg.UserID)
	var i GetAuthorizedDeviceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlantID,
		&i.ExternalID,
		&i.Name,
		&i.DeviceModelID,
		&i.Manufacturer,
		&i.Model,
		&i.DeviceType,
		&i.SourceTypeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedPlantResource = `-- name: GetAuthorizedPlantResource :one
SELECT p.id, p.organization_id, p.code, p.name
FROM plant p
WHERE p.id = $1
  AND EXISTS (
      SELECT 1 FROM user_role ur
      JOIN role r ON r.id = ur.role_id
      JOIN role_permission rp ON rp.role_id = ur.role_id
      JOIN permission pm ON pm.id = rp.permission_id
      WHERE ur.user_id = $2
        AND pm.action = $3
        AND pm.resource_type = $4
        AND (r.organization_id IS NULL OR r.organization_id = ur.organization_id)
        AND (rp.organization_id IS NULL OR rp.organization_id = ur.organization_id)
        AND (ur.organization_id IS NULL OR ur.organization_id = p.organization_id)
        AND (ur.plant_id IS NULL OR ur.plant_id = p.id)
  )
LIMIT 1
`

type GetAuthorizedPlantResourceParams struct {
	PlantID      pgtype.UUID
	UserID       pgtype.UUID
	Action       string
	ResourceType string
}

type GetAuthorizedPlantResourceRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
}

func (q *Queries) GetAuthorizedPlantResource(ctx context.Context, arg GetAuthorizedPlantResourceParams) (GetAuthorizedPlantResourceRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedPlantResource,
		arg.PlantID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
	)
	var i GetAuthorizedPlantResourceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
	)
	return i, err
}

const listPlantDevices = `-- name: ListPlantDevices :many
SELECT d.id, d.organization_id, d.plant_id, d.external_id, d.name,
       d.device_model_id, dm.manufacturer, dm.model, dm.device_type,
       dm.source_type_id, d.is_active, d.created_at, d.updated_at
FROM device d
JOIN device_model dm ON dm.id = d.device_model_id
WHERE d.organization_id = $1
  AND d.plant_id = $2
ORDER BY d.name, d.external_id, d.id
LIMIT 500
`

type ListPlantDevicesParams struct {
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
}

type ListPlantDevicesRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	ExternalID     string
	Name           string
	DeviceModelID  pgtype.UUID
	Manufacturer   string
	Model          string
	DeviceType     string
	SourceTypeID   pgtype.Int4
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListPlantDevices(ctx context.Context, arg ListPlantDevicesParams) ([]ListPlantDevicesRow, error) {
	rows, err := q.db.Query(ctx, listPlantDevices, arg.OrganizationID, arg.PlantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlantDevicesRow
	for rows.Next() {
		var i ListPlantDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlantID,
			&i.ExternalID,
			&i.Name,
			&i.DeviceModelID,
			&i.Manufacturer,
			&i.Model,
			&i.DeviceType,
			&i.SourceTypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE device
SET name = $1, is_active = $2, updated_at = now()
WHERE id = $3
RETURNING id, organization_id, plant_id, external_id, name, device_model_id,
          is_active, created_at, updated_at
`

type UpdateDeviceParams struct {
	Name     string
	IsActive bool
	ID       pgtype.UUID
}

type UpdateDeviceRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	ExternalID     string
	Name           string
	DeviceModelID  pgtype.UUID
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (UpdateDeviceRow, error) {
	row := q.db.QueryRow(ctx, updateDevice, arg.Name, arg.IsActive, arg.ID)
	var i UpdateDeviceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlantID,
		&i.ExternalID,
		&i.Name,
		&i.DeviceModelID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
