// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ingestion.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateMiddlewareClient = `-- name: AuthenticateMiddlewareClient :one
SELECT id, organization_id, name, auto_onboard
FROM auth.middleware_client
WHERE key_hash = $1 AND is_active = true
LIMIT 1
`

type AuthenticateMiddlewareClientRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	AutoOnboard    bool
}

func (q *Queries) AuthenticateMiddlewareClient(ctx context.Context, keyHash []byte) (AuthenticateMiddlewareClientRow, error) {
	row := q.db.QueryRow(ctx, authenticateMiddlewareClient, keyHash)
	var i AuthenticateMiddlewareClientRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AutoOnboard,
	)
	return i, err
}

const completeIngestBatch = `-- name: CompleteIngestBatch :exec
UPDATE telemetry.telemetry_ingest_batch
SET accepted_count = $1,
    duplicate_count = $2,
    rejected_count = $3,
    onboarded_plant_count = $4,
    onboarded_device_count = $5,
    errors = $6, status = 'PROCESSED', processed_at = now()
WHERE id = $7
`

type CompleteIngestBatchParams struct {
	AcceptedCount        int32
	DuplicateCount       int32
	RejectedCount        int32
	OnboardedPlantCount  int32
	OnboardedDeviceCount int32
	Errors               []byte
	ID                   pgtype.UUID
}

func (q *Queries) CompleteIngestBatch(ctx context.Context, arg CompleteIngestBatchParams) error {
	_, err := q.db.Exec(ctx, completeIngestBatch,
		arg.AcceptedCount,
		arg.DuplicateCount,
		arg.RejectedCount,
		arg.OnboardedPlantCount,
		arg.OnboardedDeviceCount,
		arg.Errors,
		arg.ID,
	)
	return err
}

const createInventoryAuditEvent = `-- name: CreateInventoryAuditEvent :exec
INSERT INTO audit_log (
    organization_id, action, target_type, target_id, after_data, correlation_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreateInventoryAuditEventParams struct {
	OrganizationID pgtype.UUID
	Action         string
	TargetType     string
	TargetID       pgtype.UUID
	AfterData      []byte
	CorrelationID  pgtype.UUID
}

func (q *Queries) CreateInventoryAuditEvent(ctx context.Context, arg CreateInventoryAuditEventParams) error {
	_, err := q.db.Exec(ctx, createInventoryAuditEvent,
		arg.OrganizationID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.AfterData,
		arg.CorrelationID,
	)
	return err
}

const createOrGetIngestBatch = `-- name: CreateOrGetIngestBatch :one
INSERT INTO telemetry.telemetry_ingest_batch (
    id, organization_id, middleware_client_id, idempotency_key, payload_hash, raw_payload
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (middleware_client_id, idempotency_key) DO UPDATE
SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, payload_hash, status, accepted_count, duplicate_count, rejected_count,
          onboarded_plant_count, onboarded_device_count, errors
`

type CreateOrGetIngestBatchParams struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	MiddlewareClientID pgtype.UUID
	IdempotencyKey     string
	PayloadHash        []byte
	RawPayload         []byte
}

type CreateOrGetIngestBatchRow struct {
	ID                   pgtype.UUID
	PayloadHash          []byte
	Status               string
	AcceptedCount        int32
	DuplicateCount       int32
	RejectedCount        int32
	OnboardedPlantCount  int32
	OnboardedDeviceCount int32
	Errors               []byte
}

func (q *Queries) CreateOrGetIngestBatch(ctx context.Context, arg CreateOrGetIngestBatchParams) (CreateOrGetIngestBatchRow, error) {
	row := q.db.QueryRow(ctx, createOrGetIngestBatch,
		arg.ID,
		arg.OrganizationID,
		arg.MiddlewareClientID,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.RawPayload,
	)
	var i CreateOrGetIngestBatchRow
	err := row.Scan(
		&i.ID,
		&i.PayloadHash,
		&i.Status,
		&i.AcceptedCount,
		&i.DuplicateCount,
		&i.RejectedCount,
		&i.OnboardedPlantCount,
		&i.OnboardedDeviceCount,
		&i.Errors,
	)
	return i, err
}

const getIngestionDevice = `-- name: GetIngestionDevice :one
SELECT id, organization_id, plant_id, device_model_id, external_id, name, is_active
FROM plant.device
WHERE organization_id = $1
  AND plant_id = $2
  AND external_id = $3
LIMIT 1
`

type GetIngestionDeviceParams struct {
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	ExternalID     string
}

type GetIngestionDeviceRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	DeviceModelID  pgtype.UUID
	ExternalID     string
	Name           string
	IsActive       bool
}

func (q *Queries) GetIngestionDevice(ctx context.Context, arg GetIngestionDeviceParams) (GetIngestionDeviceRow, error) {
	row := q.db.QueryRow(ctx, getIngestionDevice, arg.OrganizationID, arg.PlantID, arg.ExternalID)
	var i GetIngestionDeviceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlantID,
		&i.DeviceModelID,
		&i.ExternalID,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const getIngestionPlant = `-- name: GetIngestionPlant :one
SELECT id, organization_id, code, name, is_active
FROM plant.plant
WHERE organization_id = $1 AND code = $2
LIMIT 1
`

type GetIngestionPlantParams struct {
	OrganizationID pgtype.UUID
	Code           string
}

type GetIngestionPlantRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
	IsActive       bool
}

func (q *Queries) GetIngestionPlant(ctx context.Context, arg GetIngestionPlantParams) (GetIngestionPlantRow, error) {
	row := q.db.QueryRow(ctx, getIngestionPlant, arg.OrganizationID, arg.Code)
	var i GetIngestionPlantRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const insertTelemetryReading = `-- name: InsertTelemetryReading :one
INSERT INTO telemetry.telemetry_reading (
    id, organization_id, plant_id, device_id, middleware_client_id, ingest_batch_id,
    gateway_id, external_key, observed_at, data_item_map, parameter_count
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11
)
ON CONFLICT (middleware_client_id, external_key, observed_at) DO NOTHING
RETURNING id
`

type InsertTelemetryReadingParams struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	PlantID            pgtype.UUID
	DeviceID           pgtype.UUID
	MiddlewareClientID pgtype.UUID
	IngestBatchID      pgtype.UUID
	GatewayID          string
	ExternalKey        string
	ObservedAt         pgtype.Timestamptz
	DataItemMap        []byte
	ParameterCount     int32
}

func (q *Queries) InsertTelemetryReading(ctx context.Context, arg InsertTelemetryReadingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTelemetryReading,
		arg.ID,
		arg.OrganizationID,
		arg.PlantID,
		arg.DeviceID,
		arg.MiddlewareClientID,
		arg.IngestBatchID,
		arg.GatewayID,
		arg.ExternalKey,
		arg.ObservedAt,
		arg.DataItemMap,
		arg.ParameterCount,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const middlewareClientPullConfig = `-- name: MiddlewareClientPullConfig :one
SELECT poll_interval_seconds, api_polling_enabled
FROM auth.middleware_client
WHERE id = $1
`

type MiddlewareClientPullConfigRow struct {
	PollIntervalSeconds int32
	ApiPollingEnabled   bool
}

func (q *Queries) MiddlewareClientPullConfig(ctx context.Context, id pgtype.UUID) (MiddlewareClientPullConfigRow, error) {
	row := q.db.QueryRow(ctx, middlewareClientPullConfig, id)
	var i MiddlewareClientPullConfigRow
	err := row.Scan(&i.PollIntervalSeconds, &i.ApiPollingEnabled)
	return i, err
}

const onboardDevice = `-- name: OnboardDevice :one
INSERT INTO plant.device (
    id, organization_id, plant_id, device_model_id, external_id, name, source_metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (organization_id, plant_id, external_id) DO UPDATE SET external_id = EXCLUDED.external_id
RETURNING id, organization_id, plant_id, device_model_id, external_id, name,
          is_active, (xmax = 0) AS created
`

type OnboardDeviceParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	DeviceModelID  pgtype.UUID
	ExternalID     string
	Name           string
	SourceMetadata []byte
}

type OnboardDeviceRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	DeviceModelID  pgtype.UUID
	ExternalID     string
	Name           string
	IsActive       bool
	Created        bool
}

func (q *Queries) OnboardDevice(ctx context.Context, arg OnboardDeviceParams) (OnboardDeviceRow, error) {
	row := q.db.QueryRow(ctx, onboardDevice,
		arg.ID,
		arg.OrganizationID,
		arg.PlantID,
		arg.DeviceModelID,
		arg.ExternalID,
		arg.Name,
		arg.SourceMetadata,
	)
	var i OnboardDeviceRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlantID,
		&i.DeviceModelID,
		&i.ExternalID,
		&i.Name,
		&i.IsActive,
		&i.Created,
	)
	return i, err
}

const onboardDeviceModel = `-- name: OnboardDeviceModel :one
INSERT INTO plant.device_model (
    id, organization_id, manufacturer, model, device_type, source_type_id
) VALUES (
    $1, $2, 'Middleware', $3,
    $4, $5
)
ON CONFLICT (organization_id, manufacturer, model) DO UPDATE SET model = EXCLUDED.model
RETURNING id, organization_id, manufacturer, model, device_type, source_type_id,
          is_active, (xmax = 0) AS created
`

type OnboardDeviceModelParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Model          string
	DeviceType     string
	SourceTypeID   pgtype.Int4
}

type OnboardDeviceModelRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Manufacturer   string
	Model          string
	DeviceType     string
	SourceTypeID   pgtype.Int4
	IsActive       bool
	Created        bool
}

func (q *Queries) OnboardDeviceModel(ctx context.Context, arg OnboardDeviceModelParams) (OnboardDeviceModelRow, error) {
	row := q.db.QueryRow(ctx, onboardDeviceModel,
		arg.ID,
		arg.OrganizationID,
		arg.Model,
		arg.DeviceType,
		arg.SourceTypeID,
	)
	var i OnboardDeviceModelRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Manufacturer,
		&i.Model,
		&i.DeviceType,
		&i.SourceTypeID,
		&i.IsActive,
		&i.Created,
	)
	return i, err
}

const onboardPlant = `-- name: OnboardPlant :one
INSERT INTO plant.plant (id, organization_id, code, name, timezone)
VALUES ($1, $2, $3, $4, 'Asia/Bangkok')
ON CONFLICT (organization_id, code) DO UPDATE SET code = EXCLUDED.code
RETURNING id, organization_id, code, name, is_active, (xmax = 0) AS created
`

type OnboardPlantParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
}

type OnboardPlantRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
	IsActive       bool
	Created        bool
}

func (q *Queries) OnboardPlant(ctx context.Context, arg OnboardPlantParams) (OnboardPlantRow, error) {
	row := q.db.QueryRow(ctx, onboardPlant,
		arg.ID,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
	)
	var i OnboardPlantRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.Created,
	)
	return i, err
}

const touchMiddlewareClient = `-- name: TouchMiddlewareClient :exec
UPDATE auth.middleware_client SET last_seen_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TouchMiddlewareClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchMiddlewareClient, id)
	return err
}

const upsertTelemetryLatest = `-- name: UpsertTelemetryLatest :exec
INSERT INTO telemetry.telemetry_latest (
    organization_id, plant_id, device_id, telemetry_reading_id, gateway_id,
    observed_at, received_at, data_item_map, parameter_count
)
SELECT organization_id, plant_id, device_id, id, gateway_id,
       observed_at, received_at, data_item_map, parameter_count
FROM telemetry.telemetry_reading
WHERE id = $1
ON CONFLICT (organization_id, device_id) DO UPDATE
SET plant_id = EXCLUDED.plant_id,
    telemetry_reading_id = EXCLUDED.telemetry_reading_id,
    gateway_id = EXCLUDED.gateway_id,
    observed_at = EXCLUDED.observed_at,
    received_at = EXCLUDED.received_at,
    data_item_map = EXCLUDED.data_item_map,
    parameter_count = EXCLUDED.parameter_count,
    updated_at = now()
WHERE (EXCLUDED.observed_at, EXCLUDED.received_at, EXCLUDED.telemetry_reading_id) >
      (telemetry.telemetry_latest.observed_at, telemetry.telemetry_latest.received_at, telemetry.telemetry_latest.telemetry_reading_id)
`

func (q *Queries) UpsertTelemetryLatest(ctx context.Context, readingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertTelemetryLatest, readingID)
	return err
}
