// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	Email             string
	Username          pgtype.Text
	DisplayName       string
	PasswordHash      string
	Status            string
	FailedLoginCount  int32
	LockedUntil       pgtype.Timestamptz
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AssetGroup struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	ParentID       pgtype.UUID
	GroupType      string
	Code           string
	Name           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AuditLog struct {
	ID             int64
	OrganizationID pgtype.UUID
	ActorUserID    pgtype.UUID
	Action         string
	TargetType     string
	TargetID       pgtype.UUID
	BeforeData     []byte
	AfterData      []byte
	SourceIp       *netip.Addr
	CorrelationID  pgtype.UUID
	OccurredAt     pgtype.Timestamptz
}

type AuthAttempt struct {
	ID         int64
	Identifier string
	SourceIp   *netip.Addr
	Success    bool
	CreatedAt  pgtype.Timestamptz
}

type Device struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	AssetGroupID   pgtype.UUID
	DeviceModelID  pgtype.UUID
	ExternalID     string
	Name           string
	SerialNumber   pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SourceMetadata []byte
}

type DeviceModel struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Manufacturer   string
	Model          string
	DeviceType     string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SourceTypeID   pgtype.Int4
}

type MiddlewareClient struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	KeyPrefix      string
	KeyHash        []byte
	AutoOnboard    bool
	IsActive       bool
	LastSeenAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PasswordRecoveryAttempt struct {
	ID         int64
	Operation  string
	Identifier string
	SourceIp   *netip.Addr
	Success    bool
	CreatedAt  pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	TokenHash      []byte
	ExpiresAt      pgtype.Timestamptz
	UsedAt         pgtype.Timestamptz
	RequestedIp    *netip.Addr
	CreatedAt      pgtype.Timestamptz
}

type Permission struct {
	ID           pgtype.UUID
	Action       string
	ResourceType string
	Description  string
}

type Plant struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Code           string
	Name           string
	Timezone       string
	Latitude       pgtype.Float8
	Longitude      pgtype.Float8
	InstalledDcKw  pgtype.Numeric
	InstalledAcKw  pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Role struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    string
	IsSystem       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RolePermission struct {
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
	PermissionID   pgtype.UUID
}

type TelemetryIngestBatch struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	MiddlewareClientID   pgtype.UUID
	IdempotencyKey       string
	PayloadHash          []byte
	RawPayload           []byte
	AcceptedCount        int32
	DuplicateCount       int32
	RejectedCount        int32
	OnboardedPlantCount  int32
	OnboardedDeviceCount int32
	Errors               []byte
	Status               string
	ReceivedAt           pgtype.Timestamptz
	ProcessedAt          pgtype.Timestamptz
}

type TelemetryReading struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	PlantID            pgtype.UUID
	DeviceID           pgtype.UUID
	MiddlewareClientID pgtype.UUID
	IngestBatchID      pgtype.UUID
	GatewayID          string
	ExternalKey        string
	ObservedAt         pgtype.Timestamptz
	ReceivedAt         pgtype.Timestamptz
	DataItemMap        []byte
	ParameterCount     int32
}

type UserRole struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	RoleID         pgtype.UUID
	PlantID        pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type UserSession struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	TokenHash      []byte
	ExpiresAt      pgtype.Timestamptz
	IdleExpiresAt  pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	ClientIp       *netip.Addr
	UserAgent      string
	CreatedAt      pgtype.Timestamptz
	CsrfHash       []byte
}
