// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: telemetry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlantDevice = `-- name: GetPlantDevice :one
SELECT id
FROM plant.device
WHERE organization_id = $1
  AND plant_id = $2
  AND id = $3
LIMIT 1
`

type GetPlantDeviceParams struct {
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
	DeviceID       pgtype.UUID
}

func (q *Queries) GetPlantDevice(ctx context.Context, arg GetPlantDeviceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPlantDevice, arg.OrganizationID, arg.PlantID, arg.DeviceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listDeviceTelemetryHistory = `-- name: ListDeviceTelemetryHistory :many
SELECT tr.id, tr.organization_id, tr.plant_id, tr.device_id,
       d.external_id AS device_external_id, d.name AS device_name,
       tr.gateway_id, tr.observed_at, tr.received_at,
       tr.data_item_map, tr.parameter_count
FROM telemetry.telemetry_reading tr
JOIN plant.device d ON d.organization_id = tr.organization_id
             AND d.plant_id = tr.plant_id
             AND d.id = tr.device_id
WHERE tr.organization_id = $1
  AND tr.plant_id = $2
  AND tr.device_id = $3
  AND tr.observed_at >= $4
  AND tr.observed_at < $5
  AND (
      NOT $6::boolean
      OR (tr.observed_at, tr.received_at, tr.id) <
         ($7, $8, $9)
  )
ORDER BY tr.observed_at DESC, tr.received_at DESC, tr.id DESC
LIMIT $10
`

type ListDeviceTelemetryHistoryParams struct {
	OrganizationID   pgtype.UUID
	PlantID          pgtype.UUID
	DeviceID         pgtype.UUID
	FromTime         pgtype.Timestamptz
	ToTime           pgtype.Timestamptz
	CursorSet        bool
	CursorObservedAt pgtype.Timestamptz
	CursorReceivedAt pgtype.Timestamptz
	CursorID         pgtype.Timestamptz
	PageLimit        int32
}

type ListDeviceTelemetryHistoryRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	PlantID          pgtype.UUID
	DeviceID         pgtype.UUID
	DeviceExternalID string
	DeviceName       string
	GatewayID        string
	ObservedAt       pgtype.Timestamptz
	ReceivedAt       pgtype.Timestamptz
	DataItemMap      []byte
	ParameterCount   int32
}

// NOTE: internal/core/telemetry.go has a hand-written duplicate of this
// query (listDeviceTelemetryHistorySQL) working around an sqlc cursor-type
// inference bug — if you change this query's shape, update that too.
func (q *Queries) ListDeviceTelemetryHistory(ctx context.Context, arg ListDeviceTelemetryHistoryParams) ([]ListDeviceTelemetryHistoryRow, error) {
	rows, err := q.db.Query(ctx, listDeviceTelemetryHistory,
		arg.OrganizationID,
		arg.PlantID,
		arg.DeviceID,
		arg.FromTime,
		arg.ToTime,
		arg.CursorSet,
		arg.CursorObservedAt,
		arg.CursorReceivedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeviceTelemetryHistoryRow
	for rows.Next() {
		var i ListDeviceTelemetryHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlantID,
			&i.DeviceID,
			&i.DeviceExternalID,
			&i.DeviceName,
			&i.GatewayID,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.DataItemMap,
			&i.ParameterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPlantTelemetry = `-- name: ListLatestPlantTelemetry :many
SELECT latest.telemetry_reading_id AS id, latest.organization_id, latest.plant_id, latest.device_id,
       d.external_id AS device_external_id, d.name AS device_name,
       latest.gateway_id, latest.observed_at, latest.received_at,
       latest.data_item_map, latest.parameter_count
FROM telemetry.raw_telemetry_latest latest
JOIN plant.device d ON d.organization_id = latest.organization_id
             AND d.plant_id = latest.plant_id
             AND d.id = latest.device_id
WHERE latest.organization_id = $1
  AND latest.plant_id = $2
ORDER BY d.name, d.external_id, d.id
LIMIT 500
`

type ListLatestPlantTelemetryParams struct {
	OrganizationID pgtype.UUID
	PlantID        pgtype.UUID
}

type ListLatestPlantTelemetryRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	PlantID          pgtype.UUID
	DeviceID         pgtype.UUID
	DeviceExternalID string
	DeviceName       string
	GatewayID        string
	ObservedAt       pgtype.Timestamptz
	ReceivedAt       pgtype.Timestamptz
	DataItemMap      []byte
	ParameterCount   int32
}

func (q *Queries) ListLatestPlantTelemetry(ctx context.Context, arg ListLatestPlantTelemetryParams) ([]ListLatestPlantTelemetryRow, error) {
	rows, err := q.db.Query(ctx, listLatestPlantTelemetry, arg.OrganizationID, arg.PlantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestPlantTelemetryRow
	for rows.Next() {
		var i ListLatestPlantTelemetryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlantID,
			&i.DeviceID,
			&i.DeviceExternalID,
			&i.DeviceName,
			&i.GatewayID,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.DataItemMap,
			&i.ParameterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
